import pennylane as qml
from pennylane import numpy as np
import random

# Create a quantum device
dev = qml.device("default.qubit", wires=1)

# Define a quantum circuit


@qml.qnode(dev)
def quantum_random_number_generator():
    qml.Hadamard(0)
    return qml.probs(wires=[0])


def main():
    print("Welcome to the Quantum Random Number Generator Game!")
    print("You need to guess the outcome of a random bit generated by a quantum circuit.")
    print("Enter either 0 or 1 to make your guess.")

    user_input = input("Your guess: ")
    while user_input not in ["0", "1"]:
        user_input = input("Invalid input! Enter either 0 or 1: ")

    probs = quantum_random_number_generator()
    quantum_random_number = np.random.choice([0, 1], p=probs)

    print(f"Quantum random number: {quantum_random_number}")

    if int(user_input) == quantum_random_number:
        print("Congratulations! Your guess is correct!")
    else:
        print("Oops! Better luck next time!")


if __name__ == '__main__':
    main()
